#!/bin/sh
sed -i 's/\t/    /g' *.c
for cfile in `ls *c | grep "^Thread"`
do
	file=${cfile%.c}
	if [ -f $file ]
	then
		rm $file
		gcc -o $file $cfile -lpthread
	else
		gcc -o $file $cfile -lpthread
	fi	
done

for cfile in `ls *c | grep -v "^Thread"`
do
	file=${cfile%.c}
	if [ -f $file ]
	then
		rm $file
		gcc -o $file $cfile 
	else
		gcc -o $file $cfile
	fi	
done
echo "build all"
