#!/bin/sh
sed -i 's/\t/    /g' *.c
for cfile in `ls *c `
do
	file=${cfile%.c}
	if [ -f $file ]
	then
		rm $file
		gcc -o $file $cfile -lpthread
	else
		gcc -o $file $cfile -lpthread
	fi	
done
echo "build all "
